### ISSUE TITLE
Issue with filtering genes

### ISSUE THREAD

**Issue by CGEatTuebingen** [RHReynolds/RBD-GWAS-analysis#1]
Issue with fitlering genes

Hi, 
Thanks for great work and making everything available, allowing others to learn.

While trying to work with my own datasets:

I landed with issues in filtering genes during the coloc analysis (during looping), I land up with an error, in both the blood and brain analysis. You have chosen to use different methods to filter in both the cases:

**Case 1:**
coloc_RBD_eQTLGen.R

 eQTL_tidy_gene_filtered <- 
    eQTL %>% 
    **dplyr::filter(Gene == ensembl_gene_id_to_search)** %>%
    colochelpR::tidy_eQTL_eQTLGen() %>% 
    colochelpR::check_coloc_data_format(beta_or_pval = "pval", check_maf = F) %>% 
    dplyr::distinct(SNP, .keep_all = T)

**Error:**
Error in `dplyr::filter()`:
! Problem while computing `..1 = Gene == ensembl_gene_id_to_search$ensembl_id`.
x Input `..1` must be of size 127341798 or 1, not size 0.
Backtrace:
  1. ... %>% dplyr::distinct(SNP, .keep_all = T)
 12. dplyr:::filter.data.frame(., Gene == ensembl_gene_id_to_search$ensembl_id)

**Case 2:**
coloc_RBD_psychencode.R
eQTL_tidy_gene_filtered <- 
    eQTL %>% 
    **dplyr::filter(str_detect(gene_id, ensembl_gene_id_to_search))** %>%
    colochelpR::tidy_eQTL_psychencode(., psychencode_SNP_info = SNP_info, add_colnames = F) %>% 
    colochelpR::check_coloc_data_format(beta_or_pval = "pval", check_maf = F) %>% 
    dplyr::distinct(SNP, .keep_all = T)

**Error:**
Error in `dplyr::filter()`:
! Problem while computing `..1 = Gene == ensembl_gene_id_to_search`.
x Input `..1` must be of size 1325228 or 1, not size 8320.
Backtrace:
  1. ... %>% dplyr::distinct(SNP, .keep_all = T)
 12. dplyr:::filter.data.frame(., Gene == ensembl_gene_id_to_search)

_Somehow, I solved the issue, but I am not exactly sure if its correct, as it may interfere with the looping:_

CASE 1

eQTL_tidy_gene_filtered <- 
    eQTL %>% 
    **dplyr::filter(Gene %in% ensembl_gene_id_to_search$ensembl_id)** %>%
    colochelpR::tidy_eQTL_eQTLGen() %>% 
    colochelpR::check_coloc_data_format(beta_or_pval = "pval", check_maf = F) %>% 
    dplyr::distinct(SNP, .keep_all = T)

CASE 2

eQTL_tidy_gene_filtered <- 
    eQTL %>% 
    **dplyr::filter(gene_id %in% ensembl_gene_id_to_search$ensembl_id)** %>%
    colochelpR::tidy_eQTL_eQTLGen() %>% 
    colochelpR::check_coloc_data_format(beta_or_pval = "pval", check_maf = F) %>% 
    dplyr::distinct(SNP, .keep_all = T)

Could you please help me. Thanks.

**Comment by RHReynolds** [comment]
Hi!

Glad to hear the code is proving useful :)

So a little bit of background re. the two filtering methods, using the gene SNCA (ENSG00000145335) as an example:

1. Ensembl gene identifiers in the eQTLGen data are written in the form "ENSG00000145335" (or at least they were in the full cis-eQTLs file I downloaded from [eQTLGen](https://eqtlgen.org/cis-eqtls.html)). As the gene in the vector `ensembl_gene_id_to_search` is in the same format, I can use a `==` to filter.
2. Ensembl gene identifiers in the Psychencode data are written in the form "ENSG00000145335.X" where ".X" represents the annotation version. As the gene in the vector `ensembl_gene_id_to_search` does not include the annotation version, I cannot filter using `==`, as it will look for a full match. Instead I use `str_detect()`, which allows me to match based on a pattern (i.e. "ENSG00000145335"). 

In both cases, the idea is to minimise the input to the `tidy_eQTL_*()` functions, as these functions will take longer (in terms of time) the more rows that have to be "tidied".

With regards your error, I think it may be arising from what you have stored in `ensembl_gene_id_to_search`. This should be a character vector with a single ensembl gene identifier e.g. `c("ENSG00000145335")`. In the error in CASE 1 (`x Input ..1 must be of size 127341798 or 1, not size 0.`) it seems `ensembl_gene_id_to_search` is empty, while in CASE 2 (`x Input ..1 must be of size 1325228 or 1, not size 8320.`) `ensembl_gene_id_to_search` is of size 8230. The loop is designed to perform coloc across each gene, thus I'm not sure if your solution will work, as I suspect you have may have more than one gene in `eQTL_tidy_gene_filtered`.

Hopefully this helps and if not, feel free to ask again.

Best,
Regina

**Comment by Sandyyy123** [comment]
Hi Regina,
I am glad to have your help. It seems that I used a tibble dataframe from here:
https://rhreynolds.github.io/RBD-GWAS-analysis/RBD_coloc.html

ensembl_gene_ids_overlapping_1Mb_window_hit <-
  tibble(ensembl_id = ensembl_gene_ids_overlapping_1Mb_window_hit) %>% 
  colochelpR::biomart_df(.,
                         columnToFilter = "ensembl_id", 
                         attributes = c("ensembl_gene_id", "hgnc_symbol",
                                        "chromosome_name", "start_position", "end_position"),
                         filter = "ensembl_gene_id",
                         mart = 37)

So, reverted back to vector variable using the script provided by you:

ensembl_gene_ids_overlapping_1Mb_window_hit <- 
  RBD_tidy_w_varbeta %>% 
  tidyr::separate(col = SNP, into = c("CHR", "BP"), sep = ":", remove = FALSE) %>% 
  dplyr::mutate(CHR = as.integer(CHR),
                BP = as.integer(BP)) %>% 
  colochelpR::get_genes_within_1Mb_of_signif_SNPs(pvalue_column = "p.value",
                                                  CHR_column = "CHR",
                                                  BP_column = "BP",
                                                  mart = 37)


And thank you letting me know why str_detect was used.

The problem appears to be resolved now.

Thanks.
Regards
Sandeep

**Comment by RHReynolds** [comment]
Hi Sandeep,

Ah yes, I'd forgotten about that. Sorry for the confusion! And glad to hear the problem is resolved now.

If you have any other questions then please let me know.

Best,
Regina
